Make sure output segmentation fault from hmmpress

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -1,19 +1,24 @@
 #!/bin/bash
 
 if [ "$#" != "1" ]; then
-    echo "You need to provide a single argument."
+    echo >&2 "You need to provide a single argument."
     exit 1
 fi
 
 HMMFILE="/app/data/$1"
 if ! test -f "$HMMFILE"; then
-    echo "$HMMFILE does not exist."
+    echo >&2 "$HMMFILE does not exist."
     exit 1
 fi
 
-echo -n "Pressing $HMMFILE... "
-/app/bin/hmmpress "$HMMFILE" >/app/logs/h3press.log 2>&1 || exit 1
-echo "done."
+echo -n "Pressing $HMMFILE... " | tee /app/logs/h3press.log
+if { /app/bin/hmmpress "$HMMFILE"; } >>/app/logs/h3press.log 2>&1; then
+    echo "done." | tee -a /app/logs/h3press.log
+else
+    echo >&2 "Failed to press file $HMMFILE."
+    echo "failed." | tee -a /app/logs/h3press.log
+    exit 1
+fi
 
 h3master_pid=0
 h3worker_pid=0
diff --git a/h3daemon b/h3daemon
--- a/h3daemon
+++ b/h3daemon
@@ -176,7 +176,7 @@ function exec_start() {
         fi
     fi
 
-    cmd="podman run -dt -p 51371:51371"
+    cmd="podman run -d -p 51371:51371"
     cmd="$cmd -v $HMMFILE:/app/data/"$(basename "$HMMFILE")
 
     if [ -n "$LOGDIR" ]; then
@@ -192,7 +192,24 @@ function exec_start() {
     $cmd >/dev/null || exit 1
 
     echo -n "Starting h3daemon..."
+    sleep 0.1
+    if ! podman container exists h3daemon >/dev/null 2>&1; then
+        echo >&2 "Container h3daemon does not exist."
+        kill_container
+        echo " failed."
+        exit 1
+    fi
+
     trials=0
+    ERRMSG=$(podman inspect -f "{{.State.Running}}" h3daemon 2>&1 >/dev/null)
+    if [ -n "$ERRMSG" ]; then
+        echo >&2 "Container just died."
+        if podman container exists h3daemon; then
+            kill_container
+        fi
+        echo " failed."
+        exit 1
+    fi
     until [ "$(podman inspect -f "{{.State.Running}}" h3daemon)" == "true" ]; do
         echo -n .
         trials=$((trials + 1))
@@ -219,6 +236,12 @@ function exec_start() {
         done
     else
         sleep 5
+    fi
+    if ! podman container exists h3daemon >/dev/null 2>&1; then
+        echo >&2 "Container h3daemon does not exist."
+        kill_container
+        echo " failed."
+        exit 1
     fi
     echo " done."
 
