Specify inspect type, welcome msage

diff --git a/h3daemon b/h3daemon
--- a/h3daemon
+++ b/h3daemon
@@ -80,9 +80,9 @@ function podman_version_major() {
 function health_status() {
     VERSION=$(podman_version_major)
     if ((VERSION < 4)); then
-        podman inspect -f "{{.State.Healthcheck.Status}}" h3daemon
+        podman inspect -f "{{.State.Healthcheck.Status}}" -t container h3daemon
     else
-        podman inspect -f "{{.State.Health.Status}}" h3daemon
+        podman inspect -f "{{.State.Health.Status}}" -t container h3daemon
     fi
 }
 
@@ -246,17 +246,9 @@ function exec_start() {
         exit 1
     fi
 
-    trials=0
     podman inspect -f "{{.State.Runnings}}" -t container h3daemon >/dev/null 2>&1 || exit 1
-    # ERRMSG=$(podman inspect -f "{{.State.Runnings}}" h3daemon 2>&1 >/dev/null | grep "level=error")
-    # if [ -n "$ERRMSG" ]; then
-    #     echo >&2 "Container just died ($ERRMSG)."
-    #     if podman container exists h3daemon; then
-    #         kill_container
-    #     fi
-    #     echo " failed."
-    #     exit 1
-    # fi
+
+    trials=0
     until [ "$(podman inspect -f "{{.State.Running}}" -t container h3daemon)" == "true" ]; do
         echo -n .
         trials=$((trials + 1))
@@ -268,22 +260,18 @@ function exec_start() {
         sleep 0.1
     done
 
-    ERRMSG=$(health_status 2>&1 >/dev/null | grep "level=error")
-    if [ -z "$ERRMSG" ]; then
-        sleep 4
-        until [ "$(health_status)" == "healthy" ]; do
-            echo -n .
-            trials=$((trials + 1))
-            if [ "$trials" == "10" ]; then
-                echo " failed."
-                kill_container
-                exit 1
-            fi
-            sleep 3
-        done
-    else
-        sleep 5
-    fi
+    sleep 4
+    until [ "$(health_status)" == "healthy" ]; do
+        echo -n .
+        trials=$((trials + 1))
+        if [ "$trials" == "10" ]; then
+            echo " failed."
+            kill_container
+            exit 1
+        fi
+        sleep 3
+    done
+
     if ! podman container exists h3daemon >/dev/null 2>&1; then
         echo >&2 "Container h3daemon does not exist."
         kill_container
@@ -291,13 +279,14 @@ function exec_start() {
         exit 1
     fi
     echo " done."
+    echo
 
-    echo "██╗░░██╗██████╗░██████╗░░█████╗░███████╗███╗░░░███╗░█████╗░███╗░░██╗"
-    echo "██║░░██║╚════██╗██╔══██╗██╔══██╗██╔════╝████╗░████║██╔══██╗████╗░██║"
-    echo "███████║░█████╔╝██║░░██║███████║█████╗░░██╔████╔██║██║░░██║██╔██╗██║"
-    echo "██╔══██║░╚═══██╗██║░░██║██╔══██║██╔══╝░░██║╚██╔╝██║██║░░██║██║╚████║"
-    echo "██║░░██║██████╔╝██████╔╝██║░░██║███████╗██║░╚═╝░██║╚█████╔╝██║░╚███║"
-    echo "╚═╝░░╚═╝╚═════╝░╚═════╝░╚═╝░░╚═╝╚══════╝╚═╝░░░░░╚═╝░╚════╝░╚═╝░░╚══╝"
+    echo "██╗░░██╗██████╗░██████╗░░█████╗░███████╗███╗░░░███╗░█████╗░███╗░░██╗  ██╗░██████╗  ░█████╗░███╗░░██╗██╗"
+    echo "██║░░██║╚════██╗██╔══██╗██╔══██╗██╔════╝████╗░████║██╔══██╗████╗░██║  ██║██╔════╝  ██╔══██╗████╗░██║██║"
+    echo "███████║░█████╔╝██║░░██║███████║█████╗░░██╔████╔██║██║░░██║██╔██╗██║  ██║╚█████╗░  ██║░░██║██╔██╗██║██║"
+    echo "██╔══██║░╚═══██╗██║░░██║██╔══██║██╔══╝░░██║╚██╔╝██║██║░░██║██║╚████║  ██║░╚═══██╗  ██║░░██║██║╚████║╚═╝"
+    echo "██║░░██║██████╔╝██████╔╝██║░░██║███████╗██║░╚═╝░██║╚█████╔╝██║░╚███║  ██║██████╔╝  ╚█████╔╝██║░╚███║██╗"
+    echo "╚═╝░░╚═╝╚═════╝░╚═════╝░╚═╝░░╚═╝╚══════╝╚═╝░░░░░╚═╝░╚════╝░╚═╝░░╚══╝  ╚═╝╚═════╝░  ░╚════╝░╚═╝░░╚══╝╚═╝"
 }
 
 function kill_container() {
