failed possibility on starting it

diff --git a/h3daemon b/h3daemon
--- a/h3daemon
+++ b/h3daemon
@@ -188,13 +188,25 @@ function exec_start() {
     $cmd >/dev/null
 
     echo -n "Starting h3daemon..."
+    trials=0
     until [ "$(podman inspect -f "{{.State.Running}}" h3daemon)" == "true" ]; do
         echo -n .
+        trials=$((trials + 1))
+        if [ "$trials" == "10" ]; then
+            echo " failed."
+            exit 1
+        fi
         sleep 0.1
     done
 
     until [ "$(podman inspect -f "{{.State.Health.Status}}" h3daemon)" == "healthy" ]; do
         echo -n .
+        trials=$((trials + 1))
+        trials=$((trials + 1))
+        if [ "$trials" == "10" ]; then
+            echo " failed."
+            exit 1
+        fi
         sleep 1
     done
     echo " done."
