Check health only if systemd is available

diff --git a/h3daemon b/h3daemon
--- a/h3daemon
+++ b/h3daemon
@@ -183,9 +183,16 @@ function exec_start() {
         cmd="$cmd -v $LOGDIR:/app/logs"
     fi
 
+    USE_HEALTH_CHECK=false
+    if systemd -h >/dev/null 2>&1; then
+        USE_HEALTH_CHECK=true
+    fi
+
     image=quay.io/microbiome-informatics/h3daemon
-    cmd="$cmd --health-cmd=/app/bin/check-health"
-    cmd="$cmd --health-interval=2s --health-start-period=2s --health-timeout=2s"
+    if [ "$USE_HEALTH_CHECK" == "true" ]; then
+        cmd="$cmd --health-cmd=/app/bin/check-health"
+        cmd="$cmd --health-interval=2s --health-start-period=2s --health-timeout=2s"
+    fi
     cmd="$cmd --name h3daemon"
     cmd="$cmd --rm $image $(basename "$HMMFILE")"
 
@@ -204,17 +211,19 @@ function exec_start() {
         sleep 0.1
     done
 
-    until [ "$(podman inspect -f "{{.State.Health.Status}}" h3daemon)" == "healthy" ]; do
-        echo -n .
-        trials=$((trials + 1))
-        trials=$((trials + 1))
-        if [ "$trials" == "10" ]; then
-            echo " failed."
-            kill_container
-            exit 1
-        fi
-        sleep 1.5
-    done
+    if [ "$USE_HEALTH_CHECK" == "true" ]; then
+        until [ "$(podman inspect -f "{{.State.Health.Status}}" h3daemon)" == "healthy" ]; do
+            echo -n .
+            trials=$((trials + 1))
+            trials=$((trials + 1))
+            if [ "$trials" == "10" ]; then
+                echo " failed."
+                kill_container
+                exit 1
+            fi
+            sleep 1.5
+        done
+    fi
     echo " done."
 
     echo "██╗░░██╗██████╗░██████╗░░█████╗░███████╗███╗░░░███╗░█████╗░███╗░░██╗"
